version: "1.0"
  internal_phases:
    - pre:
        name: pre
        mode: parallel
        fail_fast: false
    - during:
        name: during
        mode: parallel
        fail_fast: false
    - post:
        name: post
        mode: seq
stages:
  pre:
    - name: pre-stage
      phase: pre
      internal_phases:
        - pre:
            name: pre
            mode: parallel
            fail_fast: false
        - during:
            name: during
            mode: parallel
            fail_fast: false
        - post:
            name: post
            mode: seq
  - flow:
      name: flow-stage
  - post:
     - name: post-stage
       phase: post
steps:

  pre1:
    image: "alpine:latest"
    stage: flow
    phase: pre
    commands:
      - "echo pre step 1"

  pre2:
    image: "alpine:latest"
    stage: flow
    phase: pre
    depends: pre
    commands:
      - "echo pre step 1"
  flow1:
    title: "title"
    stage: flow
    image: "alpine:latest"
    commands:
      - "echo step1"

  flow2:
    title: "title"
    stage: flow
    image: "alpine:latest"
    commands:
      - "echo step2"
    on:
      finish:
        stage: flow2
      start:
        stage: flow3

  post1:
    image: "alpine:latest"
    stage: post
    commands:
      - "echo post step 1"
  post2:
    image: "alpine:latest"
    stage: post
    commands:
      - "echo post step 2"
